version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/tests/integration"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/vendor-bin/csfixer"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/vendor-bin/mozart"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/vendor-bin/phpunit"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/vendor-bin/psalm"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable28
  open-pull-requests-limit: 10
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable27
  open-pull-requests-limit: 10
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable26
  open-pull-requests-limit: 10
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable28
  open-pull-requests-limit: 10
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable27
  open-pull-requests-limit: 10
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable26
  open-pull-requests-limit: 10
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
